### ISSUE TITLE
Installation of PETfold in the readme is misdirecting

### ISSUE THREAD

**Issue by juychen** [leeyang/DRfold#1]
Hi,
Thanks for your good work on the RNA structure prediction.
However, I found some problems installing the PETfold package.
On the homepage, you suggest

_2. How to install the DRfold?
    1) Third-party softwares
		1. PETfold (https://rth.dk/resources/petfold/download.html)
		2. The ViennaRNA Package (https://www.tbi.univie.ac.at/RNA/)
		3. Arena (https://github.com/pylelab/Arena)# If bin/Arena does not work, try to compile from thsi source_

The mentioned version of the PETfold was 1.0 in 2008.
Your shell script will fail because there is no option _PETfold -r_ in version 1.0.

You should use the version 2.0/2.1 here:
[version 2.1](https://rth.dk/resources/petfold/download.php)

and 

export PETFOLDBIN=#Your PETFOLDBIN path here#

Hope you can update the tutorial.

**Comment by leeyang** [comment]
Hi Chen,

Thank you so much for pointing it out. We are testing your suggestions. We will update the readme file soon.

Thank you!

**Comment by luwei0917** [comment]
version 2.2 of PETfold won't work. because new warning "WARNING: PETfold is cancelled as your input consists of ONLY 1 sequence(s).
Please provide an alignment of at least 3 sequences."

**Comment by leeyang** [comment]
We test the installation on another machine with PETfold v2.0 and it works fine. We have updated the readme file. Thank you again for the test.
