### ISSUE TITLE
No module named 'rigid' in DRfold/PotentialFold/Fold.py

### ISSUE THREAD

**Issue by juychen** [leeyang/DRfold#2]
ModuleNotFoundError
No module named 'rigid'
  File ".../DRfold/PotentialFold/Fold.py", line 13, in <module>
    import a2b,rigid
ModuleNotFoundError: No module named 'rigid'

**Comment by leeyang** [comment]
Hi Chen,

Thank you so much for the test. The rigid file has been uploaded. Please let me know if you have any other questions.

Best

**Comment by juychen** [comment]
> Hi Chen,
> 
> Thank you so much for the test. The rigid file has been uploaded. Please let me know if you have any other questions.
> 
> Best

Hi, 

Thanks for your update. Do you mind editing the readme according to the thread #1 ? I think that gives a clear direction to the installation of PETfold.

Regards,
Junyi
