### ISSUE TITLE
what's the base.npy?

### ISSUE THREAD

**Issue by jxzly** [leeyang/DRfold#3]
I want to know what features are in the base.npy. Anyone can tell me?

**Comment by leeyang** [comment]
Those are conformations of nucleotides after symmetric orthogonalization.

Thanks!

**Comment by jxzly** [comment]
Thanks. I'm also wondering why 1D_pos is added. Would this enhance generalization ability？
```
def compute_pos1d(self,maxL=500):
      d = torch.arange(maxL)
      m = 14
      d =(((d[:,None] & (1 << np.arange(m)))) > 0).float()
      return d
```

**Comment by leeyang** [comment]
We tried several 1-D positional embedding methods and found that they had similar performance. This 1D_pos is basic and simple, so we keep this one.
