### ISSUE TITLE
Issues with Terminal Output from Test Command

### ISSUE THREAD

**Issue by yangnianzu0515** [leeyang/DRfold#5]
My environment seems to be set up successfully. Then, I ran the test command you provided:
```
bash DRfold.sh test/seq.fasta test/DRfold_out
```
The terminal output is as follows, always displaying messages like ```Bad direction ...``` and ```Line search cannot locate an adequate point after MAXLS```. Are these normal outputs?

<img width="1059" alt="image" src="https://github.com/leeyang/DRfold/assets/51359992/fb4d4633-ae5b-47c9-80a0-f1f3426e6456">

**Comment by leeyang** [comment]
Hi, those are the warnings from lbfgs of scipy and our implementations. You can simply ignore them.
Thanks!

**Comment by yangnianzu0515** [comment]
Thank you so much for your timely response! 

I must express my deep admiration for your exemplary work; it has been profoundly enlightening for me.
